networks:
  prometheus:
    ipam:
      driver: default
      config:
        - subnet: "172.28.0.0/24"

services:
  prometheus:
    container_name: prometheus
    image: bitnami/prometheus:2.51.2
    networks:
      - prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus-data:/opt/bitnami/prometheus/data
      - ./prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml

  grafana:
    container_name: grafana
    image: grafana/grafana:10.4.2
    networks:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana-data:/var/lib/grafana